In [71]:
import pandas as pd
import numpy as np

file1 = pd.read_csv('SL88824_20180802.cnv.csv', sep = "\t")
file2 = pd.read_csv('SL88823_20180802.cnv.csv', sep = "\t")

file1['Sample#'] = 1
file2['Sample#'] = 2

file1 = file1[file1["Chrom"] != 'chrM']
file2 = file2[file2["Chrom"] != 'chrM']

In [72]:
common_cnvs = pd.DataFrame(columns = file1.columns)
print(common_cnvs.head())

Empty DataFrame
Columns: [Chrom, Start, Stop, Type, P_Value, Sample#]
Index: []

In [73]:
chrom_num = file1["Chrom"].unique()
print(chrom_num)

['chr1' 'chr2' 'chr3' 'chr4' 'chr5' 'chr6' 'chr7' 'chr8' 'chr9' 'chr10'
 'chr11' 'chr12' 'chr13' 'chr14' 'chr15' 'chr16' 'chr17' 'chr18' 'chr19'
 'chr20' 'chr21' 'chr22' 'chrX' 'chrY']

In [74]:
for i in range(len(chrom_num)):
    file1_cnvs = file1[(file1['Chrom'] == chrom_num[i])]
    file2_cnvs = file2[(file2['Chrom'] == chrom_num[i])]

    for j in range(len(file1_cnvs)):
        if(abs(file1_cnvs.iloc[j,1] - file1_cnvs.iloc[j,2]) >= 1000):
            for k in range(len(file2_cnvs)):
                if(abs(file2_cnvs.iloc[k,1] - file2_cnvs.iloc[k,2]) >= 1000):
                    if(abs(file1_cnvs.iloc[j,1] - file2_cnvs.iloc[k,1]) <= 25 and abs(file1_cnvs.iloc[j,2] - file2_cnvs.iloc[k,2]) <= 25):
                        if(file1_cnvs.iloc[j,3] == file2_cnvs.iloc[k,3]):
                             if(file1.iloc[j,4] >= .90 and file2.iloc[k,4] >= .90):
                                common_cnvs = pd.concat([common_cnvs, file1_cnvs.iloc[[j]], file2_cnvs.iloc[[k]]])

In [75]:
common_cnvs.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 58 entries, 23 to 1551
Data columns (total 6 columns):
Chrom      58 non-null object
Start      58 non-null object
Stop       58 non-null object
Type       58 non-null object
P_Value    58 non-null float64
Sample#    58 non-null object
dtypes: float64(1), object(5)
memory usage: 3.2+ KB

In [80]:
common_cnvs

      Chrom      Start       Stop         Type   P_Value Sample#
23     chr1   21689194   21690226     DELETION  0.999980       1
12     chr1   21689194   21690226     DELETION  1.000000       2
28     chr1   84246365   84249757     DELETION  1.000000       1
19     chr1   84246365   84249757     DELETION  1.000000       2
116    chr1  164079439  164082869  DUPLICATION  0.999997       1
125    chr1  164079439  164082869  DUPLICATION  1.000000       2
243    chr3  149244968  149252373     DELETION  1.000000       1
253    chr3  149244968  149252373     DELETION  1.000000       2
311    chr4   87393977   87395067     DELETION  0.999959       1
310    chr4   87393977   87395067     DELETION  1.000000       2
399    chr5   83655961   83660986     DELETION  1.000000       1
366    chr5   83655961   83660986     DELETION  1.000000       2
479    chr6   78170175   78183012     DELETION  1.000000       1
454    chr6   78170175   78183012     DELETION  1.000000       2
480    chr6   78811357   78817539     DELETION  1.000000       1
455    chr6   78811357   78817539     DELETION  1.000000       2
485    chr6  134268976  134272633     DELETION  0.999992       1
462    chr6  134268976  134272633     DELETION  0.999998       2
492    chr6      95197     124783  DUPLICATION  1.000000       1
476    chr6      95197     124783  DUPLICATION  1.000000       2
502    chr6   26753696   26768160  DUPLICATION  1.000000       1
484    chr6   26753696   26768160  DUPLICATION  1.000000       2
649    chr8    9640461    9642984     DELETION  1.000000       1
663    chr8    9640461    9642984     DELETION  1.000000       2
728    chr9   40099976   40105656     DELETION  0.999992       1
760    chr9   40099976   40105656     DELETION  0.999967       2
731    chr9   40179991   40223531     DELETION  1.000000       1
762    chr9   40179991   40223531     DELETION  1.000000       2
737    chr9   41102512   41108667     DELETION  1.000000       1
767    chr9   41102512   41108667     DELETION  1.000000       2
750    chr9   60739388   60849385     DELETION  1.000000       1
781    chr9   60739388   60849385     DELETION  1.000000       2
842   chr10  113126112  113127299     DELETION  1.000000       1
884   chr10  113126112  113127299     DELETION  0.999974       2
907   chr11  134733716  134737779     DELETION  1.000000       1
953   chr11  134733716  134737779     DELETION  1.000000       2
928   chr11   59043302   59086440  DUPLICATION  1.000000       1
973   chr11   59043302   59086440  DUPLICATION  1.000000       2
956   chr12   33233721   33240026     DELETION  1.000000       1
993   chr12   33233721   33240026     DELETION  1.000000       2
991   chr13   21844425   21847652     DELETION  0.999998       1
1038  chr13   21844425   21847652     DELETION  1.000000       2
998   chr13  105576969  105655462     DELETION  1.000000       1
1044  chr13  105576969  105655462     DELETION  1.000000       2
1029  chr14   41139526   41200321     DELETION  1.000000       1
1092  chr14   41139526   41200321     DELETION  1.000000       2
1191  chr16   21771249   21777772  DUPLICATION  1.000000       1
1276  chr16   21771249   21777772  DUPLICATION  1.000000       2
1284  chr18   79618625   79620710     DELETION  1.000000       1
1365  chr18   79618625   79620710     DELETION  1.000000       2
1389  chr21    8219531    8220541     DELETION  1.000000       1
1451  chr21    8219531    8220541     DELETION  1.000000       2
1406  chr21    8447047    8451714  DUPLICATION  1.000000       1
1478  chr21    8447047    8451714  DUPLICATION  1.000000       2
1439  chr22   38962236   38992202     DELETION  1.000000       1
1519  chr22   38962236   38992202     DELETION  1.000000       2
1471  chr22   22900485   22905851  DUPLICATION  1.000000       1
1551  chr22   22900485   22905851  DUPLICATION  1.000000       2

In [ ]:
common_cnvs.reset_index().to_csv()